name: Build on push

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/.gitignore'
      - 'images/'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/.gitignore'
      - 'images/'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
